### ISSUE TITLE
runtime old for Midterm

### ISSUE THREAD

**Issue by C4ble17** [flathub/app.midterm.MidtermDesktop#9]
I have installed the application flatpak and would like to report that when I update the flatpaks installed in the system, I get a report regarding Midterm runtimes(I attach file with report).

I ask, kindly, the possibility to update the runtimes to the latest version.
I thank you for the availability

![Schermata del 2022-12-24 13-04-20](https://user-images.githubusercontent.com/121351163/209442869-3750ff26-e20d-4e11-8ff3-4be0a2579a53.png)

**Comment by jimmyloi** [comment]
@C4ble17 Thanks for letting us know. I will upgrade the app soon.

**Comment by C4ble17** [comment]
thank you for your attention and helpfulness
